package com.example.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-21T18:14:44.824+08:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://tempuri.org", name = "PUB0015Soap")
public interface PUB0015Soap {

    @WebMethod(operationName = "HIPMessageServer", action = "http://tempuri.org/DHC.Published.PUB0015.BS.PUB0015.HIPMessageServer")
    @WebResult(name = "HIPMessageServerResult", targetNamespace = "http://tempuri.org")
    public String hipMessageServer(

            @WebParam(name = "input1", targetNamespace = "http://tempuri.org")
                    String input1,
            @WebParam(name = "input2", targetNamespace = "http://tempuri.org")
                    String input2
    );
}
